server:
  port: 8190
  servlet:
    context-path: /app
spring:
  application:
    name: springApp
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:appdb;MODE=PostgreSQL
    username: user
    password: user
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate : TRACE